# Site settings
baseURL = "https://digitalgeohack.github.io"
languageCode = "en-US"
title = "DigitalGeoHack"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
# copyright = "&copy;2019 John Armitage"

[params]

  # Metadata for search engines and social sharing
  author = "John Armitage"
  description = "Digital Geoscience Hackathon"
  shareImage = "images/logo_idea.jpg"

  # Favicon
  #favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "img/website_01.png"
      position = "left bottom"



# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution, you can check out
# the license option via the template author's website: https://onepagelove.com/split
