baseurl = "https://www.example.com/"
languageCode = "en-us"
title = "DigitalGeoHack"
theme = "type"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."


[params]
	author = "John Armitage"
	description = "Digital Geoscience Hackathon Paris 8/9th November" 
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "images/mini_logo_idea.svg"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = ""

	headerText = "Digital Geoscience Hackathon Paris 8/9th November"
	# To add a header background to the main site, save your image under static/img/yourimage.png
	# and assign "yourimage.png" to the headerImage variable. If no image path is provided, a
	# orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](https://gohugo.io/) with the [Type Theme](https://github.com/digitalcraftsman/hugo-type-theme)"

	# Set title for Hugo's opengraph template
	title = "Type theme"
	
	[taxonomies]
		# Use the series taxonomy to group blog posts in series. Related articles in the series
		# will be used by Hugo's opengraph template
  		series = "series"
		tags = "tags"
		categories = "categories"

	# Define which types of content shall be displayed on the homepage. By default Hugo uses
	# types with the most content files.
	# mainSections = []

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		homepage = true
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "digitalgeohack"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
		meetup = ""
		speackerdeck = ""
